/**
 * TypeScript interfaces for TaskInput
 * Auto-generated by Graph-OS
 */

export interface TaskInputProps {
  className?: string;
}

export interface TaskInputSignal {
  type: string;
  payload: unknown;
  timestamp: Date;
  sourceNodeId: string;
}

export interface TaskInputConfig {
  
}