/**
 * TypeScript interfaces for AppInput
 * Auto-generated by Graph-OS
 */

export interface AppInputProps {
  className?: string;
}

export interface AppInputSignal {
  type: string;
  payload: unknown;
  timestamp: Date;
  sourceNodeId: string;
}

export interface AppInputConfig {
  
}